version: "3.7"

volumes:
  peer0.did.byondz.io:

networks:
  test:
    name: fabric_test

services:
  peer0.did.byondz.io:
    container_name: peer0.did.byondz.io
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.did.byondz.io
      - CORE_PEER_ADDRESS=peer0.did.byondz.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.did.byondz.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.did.byondz.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.did.byondz.io:7051
      - CORE_PEER_LOCALMSPID=didMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.did.byondz.io:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0did"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ~/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io:/etc/hyperledger/
      - ~/peer0.did.byondz.io:/var/hyperledger/production
      - ~/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test
    extra_hosts:
      - "orderer.byondz.io:192.168.100.78"
      - "peer0.badge.byondz.io:192.168.100.110"