#!/bin/bash

function createdid() {
  #수동입력시 이상없음
  #infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/did.byondz.io/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/did.byondz.io/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@ca.did.byondz.io:7054 --caname ca-did --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-did-byondz-io-7054-ca-did.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-did-byondz-io-7054-ca-did.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-did-byondz-io-7054-ca-did.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-did-byondz-io-7054-ca-did.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy did's CA cert to did's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/tlscacerts/ca.crt"

  # Copy did's CA cert to did's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.byondz.io/tlsca"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.byondz.io/tlsca/tlsca.did.byondz.io-cert.pem"

  # Copy did's CA cert to did's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.byondz.io/ca"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.byondz.io/ca/ca.did.byondz.io-cert.pem"

  #infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-did --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null
# 클리어(02:59)
  #infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-did --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  #infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-did --id.name didadmin --id.secret didadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  #infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@ca.did.byondz.io:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/msp" --csr.hosts peer0.did.byondz.io --csr.hosts peer1.did.byondz.io --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/msp/config.yaml"

  #infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@ca.did.byondz.io:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls" --enrollment.profile tls --csr.hosts peer0.did.byondz.io --csr.hosts peer1.did.byondz.io --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  set -x
  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/keystore/"* "${PWD}/organizations/peerOrganizations/did.byondz.io/peers/peer0.did.byondz.io/tls/server.key"
  { set +x;} 2>/dev/null
  
  #infoln "Generating the user msp"
  # set -x
  fabric-ca-client enroll -u https://user1:user1pw@ca.did.byondz.io:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.byondz.io/users/User1@did.byondz.io/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.byondz.io/users/User1@did.byondz.io/msp/config.yaml"

  #infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://didadmin:didadminpw@ca.did.byondz.io:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.byondz.io/users/Admin@did.byondz.io/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.byondz.io/users/Admin@did.byondz.io/msp/config.yaml"
}

function createbadge() {
  #infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/badge.byondz.io/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/badge.byondz.io/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@ca.badge.byondz.io:8054 --caname ca-badge --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-badge-byondz-io-8054-ca-badge.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-badge-byondz-io-8054-ca-badge.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-badge-byondz-io-8054-ca-badge.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-badge-byondz-io-8054-ca-badge.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy badge's CA cert to badge's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/tlscacerts/ca.crt"

  # Copy badge's CA cert to badge's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.byondz.io/tlsca"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.byondz.io/tlsca/tlsca.badge.byondz.io-cert.pem"

  # Copy badge's CA cert to badge's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.byondz.io/ca"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.byondz.io/ca/ca.badge.byondz.io-cert.pem"

  # infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-badge --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  # infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-badge --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  # infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-badge --id.name badgeadmin --id.secret badgeadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  # infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@ca.badge.byondz.io:8054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/msp" --csr.hosts peer0.badge.byondz.io --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/msp/config.yaml"

  # infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@ca.badge.byondz.io:8054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls" --enrollment.profile tls --csr.hosts peer0.badge.byondz.io --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/keystore/"* "${PWD}/organizations/peerOrganizations/badge.byondz.io/peers/peer0.badge.byondz.io/tls/server.key"

  # infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@ca.badge.byondz.io:8054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.byondz.io/users/User1@badge.byondz.io/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.byondz.io/users/User1@badge.byondz.io/msp/config.yaml"

  # infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://badgeadmin:badgeadminpw@ca.badge.byondz.io:8054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.byondz.io/users/Admin@badge.byondz.io/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.byondz.io/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.byondz.io/users/Admin@badge.byondz.io/msp/config.yaml"
}

function createOrderer() {
  #수동입력시 이상없음
  #infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/byondz.io

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/byondz.io

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@ca.orderer.byondz.io:7054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-orderer-byondz-io-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-orderer-byondz-io-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-orderer-byondz-io-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-orderer-byondz-io-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/byondz.io/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/byondz.io/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/byondz.io/msp/tlscacerts/tlsca.byondz.io-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/byondz.io/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/byondz.io/tlsca/tlsca.byondz.io-cert.pem"

  #infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  #infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  #infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@ca.orderer.byondz.io:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/msp" --csr.hosts orderer.byondz.io --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/byondz.io/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/msp/config.yaml"

  #infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@ca.orderer.byondz.io:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls" --enrollment.profile tls --csr.hosts orderer.byondz.io --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/byondz.io/orderers/orderer.byondz.io/msp/tlscacerts/tlsca.byondz.io-cert.pem"

  #infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@ca.orderer.byondz.io:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/byondz.io/users/Admin@byondz.io/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/byondz.io/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/byondz.io/users/Admin@byondz.io/msp/config.yaml"
}
