#!/bin/bash

DOMAIN_POSTFIX="peanut.dev.byondz.io"
MODE="dev"

function createdid() {
  echo "Executing docker for create certificate PEM"

  docker-compose -f docker-compose/docker-compose-did-ca.yaml up -d 2>&1

  while :
    do
      if [ ! -f "organizations/fabric-ca/did/tls-cert.pem" ]; then
        sleep 2
      else
        break
      fi
  done

  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-did --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-did-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-did.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-did-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-did.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-did-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-did.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-did-"'${DOMAIN_POSTFIX/\./\-}'"-7054-ca-did.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy did's CA cert to did's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/tlscacerts/ca.crt"

  # Copy did's CA cert to did's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/tlsca"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/tlsca/tlsca.did.${DOMAIN_POSTFIX}-cert.pem"

  # Copy did's CA cert to did's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/ca"
  cp "${PWD}/organizations/fabric-ca/did/ca-cert.pem" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/ca/ca.did.${DOMAIN_POSTFIX}-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-did --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-did --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-did --id.name didadmin --id.secret didadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/msp" --csr.hosts peer0.did.${DOMAIN_POSTFIX} --csr.hosts peer1.did.${DOMAIN_POSTFIX} --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls" --enrollment.profile tls --csr.hosts peer0.did.${DOMAIN_POSTFIX} --csr.hosts peer1.did.${DOMAIN_POSTFIX} --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  set -x
  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/keystore/"* "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/peers/peer0.did.${DOMAIN_POSTFIX}/tls/server.key"
  { set +x;} 2>/dev/null
  
  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/users/User1@did.${DOMAIN_POSTFIX}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/users/User1@did.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://didadmin:didadminpw@localhost:7054 --caname ca-did -M "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/users/Admin@did.${DOMAIN_POSTFIX}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/did/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/did.${DOMAIN_POSTFIX}/users/Admin@did.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Kill docker"
  docker kill ca_did
  docker container rm ca_did
}

function createbadge() {
  echo "Executing docker for create certificate PEM"

  docker-compose -f docker-compose/docker-compose-badge-ca.yaml up -d 2>&1

  while :
    do
      if [ ! -f "organizations/fabric-ca/badge/tls-cert.pem" ]; then
        sleep 2
      else
        break
      fi
  done

  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-badge --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-badge-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-badge.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-badge-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-badge.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-badge-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-badge.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-badge-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-badge.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy badge's CA cert to badge's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/tlscacerts/ca.crt"

  # Copy badge's CA cert to badge's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/tlsca"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/tlsca/tlsca.badge.${DOMAIN_POSTFIX}-cert.pem"

  # Copy badge's CA cert to badge's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/ca"
  cp "${PWD}/organizations/fabric-ca/badge/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/ca/ca.badge.${DOMAIN_POSTFIX}-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-badge --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-badge --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-badge --id.name badgeadmin --id.secret badgeadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/msp" --csr.hosts peer0.badge.${DOMAIN_POSTFIX} --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls" --enrollment.profile tls --csr.hosts peer0.badge.${DOMAIN_POSTFIX} --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/keystore/"* "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/peers/peer0.badge.${DOMAIN_POSTFIX}/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/users/User1@badge.${DOMAIN_POSTFIX}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/users/User1@badge.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://badgeadmin:badgeadminpw@localhost:7054 --caname ca-badge -M "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/users/Admin@badge.${DOMAIN_POSTFIX}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badge/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badge.${DOMAIN_POSTFIX}/users/Admin@badge.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Kill docker"
  docker kill ca_badge
  docker container rm ca_badge
}

function createOrderer() {
  echo "Executing docker for create certificate PEM"

  docker-compose -f docker-compose/docker-compose-orderer-ca.yaml up -d 2>&1

  while :
    do
      if [ ! -f "organizations/fabric-ca/ordererOrg/tls-cert.pem" ]; then
        sleep 2
      else
        break
      fi
  done

  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/${DOMAIN_POSTFIX}

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-orderer-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-orderer-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-orderer-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-orderer-'"${DOMAIN_POSTFIX/\./\-}"'-7054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/msp/tlscacerts/tlsca.${DOMAIN_POSTFIX}-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/tlsca/tlsca.${DOMAIN_POSTFIX}-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/msp" --csr.hosts orderer.${DOMAIN_POSTFIX} --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls" --enrollment.profile tls --csr.hosts orderer.${DOMAIN_POSTFIX} --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/orderers/orderer.${DOMAIN_POSTFIX}/msp/tlscacerts/tlsca.${DOMAIN_POSTFIX}-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:7054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/users/Admin@${DOMAIN_POSTFIX}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/${DOMAIN_POSTFIX}/users/Admin@${DOMAIN_POSTFIX}/msp/config.yaml"

  echo "Kill docker"
  docker kill ca_orderer
  docker container rm ca_orderer
}

function prefareCAConfig() {
  SOURCE_CACONFIG="dev-fabric-ca-server-config.yaml"
  TARGET_CACONFIG="fabric-ca-server-config.yaml"

  if [[ $MODE == "PRD" || $MODE == "prd" ]]; then
    SOURCE_CACONFIG="prd-fabric-ca-server-config.yaml"
  fi

  for i in did badge ordererOrg;
    do
    cp "${PWD}/organizations/fabric-ca/${i}/${SOURCE_CACONFIG}" "${PWD}/organizations/fabric-ca/${i}/${TARGET_CACONFIG}"
  done
}

# main
if [[ $# < 1 ]]; then
  echo "Need a argument, available arguments are createdid, createbadge, createOrderer, all, and purge"
  exit 1
fi

if [[ $MODE == "PRD" || $MODE == "prd" ]];then
DOMAIN_POSTFIX="peanut.byondz.io"
fi 

prefareCAConfig

case $1 in
  "createdid")
    createdid
  ;;
  "createbadge")
    createbadge
  ;;
  "createOrderer")
    createOrderer
  ;;
  "all")
    createdid
    createbadge
    createOrderer
  ;;
  "purge")
    rm -rf ./organizations/{peerOrganizations,ordererOrganizations}
    sudo rm -rf ./organizations/fabric-ca/{did,badge,ordererOrg}/msp
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/ca-cert.pem
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/fabric-ca-server.db
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/IssuerPublicKey
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/IssuerRevocationPublicKey
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/tls-cert.pem
    rm -f ./organizations/fabric-ca/{did,badge,ordererOrg}/fabric-ca-server-config.yaml
  ;;
esac